// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: Transport
package helloworld

import (
	context "context"
	fmt "fmt"
	math "math"

	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

type Transport interface {
	TestStream(ctx context.Context, opts ...client.CallOption) (Transport_TestStreamService, error)
	TestStream1(ctx context.Context, opts ...client.CallOption) (Transport_TestStream1Service, error)
	TestStream2(ctx context.Context, in *Message, opts ...client.CallOption) (Transport_TestStream2Service, error)
	TestStream3(ctx context.Context, in *Message, opts ...client.CallOption) (*Message, error)
}
