// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: examples/tpl/helper/import.gohtml

package helper

import (
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Import generates examples/tpl/helper/import.gohtml
func Import(isImport bool) string {
	var _b strings.Builder
	RenderImport(&_b, isImport)
	return _b.String()
}

// RenderImport render examples/tpl/helper/import.gohtml
func RenderImport(_buffer io.StringWriter, isImport bool) {
	// Line: 3
	_buffer.WriteString("\n\nimport (\n\t")
	if isImport {

		// Line: 7
		_buffer.WriteString((`_ "github.com/pubgo/gotests/gorazor/examples/models"`))

		// Line: 8
		_buffer.WriteString((`prometheus.MustRegister(isImport)`))

		// Line: 9
		_buffer.WriteString("<title>")
		// Line: 9
		_buffer.WriteString(gorazor.HTMLEscape(title))
		// Line: 9
		_buffer.WriteString("</title>")

	}
	// Line: 10
	_buffer.WriteString("\n)")

}
