// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: examples/tpl/helper/msg.gohtml

package helper

import (
	"github.com/pubgo/gotests/gorazor/examples/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Msg generates examples/tpl/helper/msg.gohtml
func Msg(u *models.User) string {
	var _b strings.Builder
	RenderMsg(&_b, u)
	return _b.String()
}

// RenderMsg render examples/tpl/helper/msg.gohtml
func RenderMsg(_buffer io.StringWriter, u *models.User) {

	username := u.Name
	if u.Email != "" {
		username += "(" + u.Email + ")"
	}

	// Line: 14
	_buffer.WriteString("\n\n\n<div class=\"welcome\">\n<h4>Hello ")
	// Line: 18
	_buffer.WriteString(gorazor.HTMLEscStr(username))
	// Line: 18
	_buffer.WriteString("</h4>\n\n<div>")
	// Line: 20
	_buffer.WriteString((u.Intro))
	// Line: 20
	_buffer.WriteString("</div>\n</div>")

}
