// Code generated by qtc from "greetings.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Greetings greets up to 42 names.
// It also greets John differently comparing to others.

//line templates/greetings.qtpl:3
package templates

//line templates/greetings.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/greetings.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/greetings.qtpl:3
func StreamGreetings(qw422016 *qt422016.Writer, names []string) {
//line templates/greetings.qtpl:3
	qw422016.N().S(`
    `)
//line templates/greetings.qtpl:4
	if len(names) == 0 {
//line templates/greetings.qtpl:4
		qw422016.N().S(`
        Nobody to greet :(
        `)
//line templates/greetings.qtpl:6
		return
//line templates/greetings.qtpl:7
	}
//line templates/greetings.qtpl:7
	qw422016.N().S(`

    `)
//line templates/greetings.qtpl:9
	for i, name := range names {
//line templates/greetings.qtpl:9
		qw422016.N().S(`
        `)
//line templates/greetings.qtpl:10
		if i == 42 {
//line templates/greetings.qtpl:10
			qw422016.N().S(`
            I'm tired to greet so many people...
            `)
//line templates/greetings.qtpl:12
			break
//line templates/greetings.qtpl:13
		} else if name == "John" {
//line templates/greetings.qtpl:13
			qw422016.N().S(`
            `)
//line templates/greetings.qtpl:14
			streamsayHi(qw422016, "Mr. "+name)
//line templates/greetings.qtpl:14
			qw422016.N().S(`
            `)
//line templates/greetings.qtpl:15
			continue
//line templates/greetings.qtpl:16
		} else {
//line templates/greetings.qtpl:16
			qw422016.N().S(`
            `)
//line templates/greetings.qtpl:17
			StreamHello(qw422016, name)
//line templates/greetings.qtpl:17
			qw422016.N().S(`
        `)
//line templates/greetings.qtpl:18
		}
//line templates/greetings.qtpl:18
		qw422016.N().S(`
    `)
//line templates/greetings.qtpl:19
	}
//line templates/greetings.qtpl:19
	qw422016.N().S(`
`)
//line templates/greetings.qtpl:20
}

//line templates/greetings.qtpl:20
func WriteGreetings(qq422016 qtio422016.Writer, names []string) {
//line templates/greetings.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/greetings.qtpl:20
	StreamGreetings(qw422016, names)
//line templates/greetings.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line templates/greetings.qtpl:20
}

//line templates/greetings.qtpl:20
func Greetings(names []string) string {
//line templates/greetings.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/greetings.qtpl:20
	WriteGreetings(qb422016, names)
//line templates/greetings.qtpl:20
	qs422016 := string(qb422016.B)
//line templates/greetings.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/greetings.qtpl:20
	return qs422016
//line templates/greetings.qtpl:20
}

// sayHi is unexported, since it starts with lowercase letter.

//line templates/greetings.qtpl:23
func streamsayHi(qw422016 *qt422016.Writer, name string) {
//line templates/greetings.qtpl:23
	qw422016.N().S(`
    Hi, `)
//line templates/greetings.qtpl:24
	qw422016.E().S(name)
//line templates/greetings.qtpl:24
	qw422016.N().S(`
`)
//line templates/greetings.qtpl:25
}

//line templates/greetings.qtpl:25
func writesayHi(qq422016 qtio422016.Writer, name string) {
//line templates/greetings.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/greetings.qtpl:25
	streamsayHi(qw422016, name)
//line templates/greetings.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line templates/greetings.qtpl:25
}

//line templates/greetings.qtpl:25
func sayHi(name string) string {
//line templates/greetings.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/greetings.qtpl:25
	writesayHi(qb422016, name)
//line templates/greetings.qtpl:25
	qs422016 := string(qb422016.B)
//line templates/greetings.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/greetings.qtpl:25
	return qs422016
//line templates/greetings.qtpl:25
}

// Note that every template file may contain an arbitrary number
// of template functions. For instance, this file contains Greetings and sayHi
// functions.
//

//line templates/greetings.qtpl:32
type MarshalRow struct {
	Msg string
	N   int
}

type MarshalData struct {
	Foo  int
	Bar  string
	Rows []MarshalRow
}

// JSON marshaling

//line templates/greetings.qtpl:46
func (d *MarshalData) StreamJSON(qw422016 *qt422016.Writer) {
//line templates/greetings.qtpl:46
	qw422016.N().S(`{"Foo":`)
//line templates/greetings.qtpl:48
	qw422016.N().D(d.Foo)
//line templates/greetings.qtpl:48
	qw422016.N().S(`,"Bar":`)
//line templates/greetings.qtpl:49
	qw422016.N().Q(d.Bar)
//line templates/greetings.qtpl:49
	qw422016.N().S(`,"Rows":[`)
//line templates/greetings.qtpl:51
	for i, r := range d.Rows {
//line templates/greetings.qtpl:51
		qw422016.N().S(`{"Msg":`)
//line templates/greetings.qtpl:53
		qw422016.N().Q(r.Msg)
//line templates/greetings.qtpl:53
		qw422016.N().S(`,"N":`)
//line templates/greetings.qtpl:54
		qw422016.N().D(r.N)
//line templates/greetings.qtpl:54
		qw422016.N().S(`}`)
//line templates/greetings.qtpl:56
		if i+1 < len(d.Rows) {
//line templates/greetings.qtpl:56
			qw422016.N().S(`,`)
//line templates/greetings.qtpl:56
		}
//line templates/greetings.qtpl:57
	}
//line templates/greetings.qtpl:57
	qw422016.N().S(`]}`)
//line templates/greetings.qtpl:60
}

//line templates/greetings.qtpl:60
func (d *MarshalData) WriteJSON(qq422016 qtio422016.Writer) {
//line templates/greetings.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/greetings.qtpl:60
	d.StreamJSON(qw422016)
//line templates/greetings.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line templates/greetings.qtpl:60
}

//line templates/greetings.qtpl:60
func (d *MarshalData) JSON() string {
//line templates/greetings.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/greetings.qtpl:60
	d.WriteJSON(qb422016)
//line templates/greetings.qtpl:60
	qs422016 := string(qb422016.B)
//line templates/greetings.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/greetings.qtpl:60
	return qs422016
//line templates/greetings.qtpl:60
}

// XML marshalling

//line templates/greetings.qtpl:65
func (d *MarshalData) StreamXML(qw422016 *qt422016.Writer) {
//line templates/greetings.qtpl:65
	qw422016.N().S(`<MarshalData><Foo>`)
//line templates/greetings.qtpl:67
	qw422016.N().D(d.Foo)
//line templates/greetings.qtpl:67
	qw422016.N().S(`</Foo><Bar>`)
//line templates/greetings.qtpl:68
	qw422016.E().S(d.Bar)
//line templates/greetings.qtpl:68
	qw422016.N().S(`</Bar><Rows>`)
//line templates/greetings.qtpl:70
	for _, r := range d.Rows {
//line templates/greetings.qtpl:70
		qw422016.N().S(`<Row><Msg>`)
//line templates/greetings.qtpl:72
		qw422016.E().S(r.Msg)
//line templates/greetings.qtpl:72
		qw422016.N().S(`</Msg><N>`)
//line templates/greetings.qtpl:73
		qw422016.N().D(r.N)
//line templates/greetings.qtpl:73
		qw422016.N().S(`</N></Row>`)
//line templates/greetings.qtpl:75
	}
//line templates/greetings.qtpl:75
	qw422016.N().S(`</Rows></MarshalData>`)
//line templates/greetings.qtpl:78
}

//line templates/greetings.qtpl:78
func (d *MarshalData) WriteXML(qq422016 qtio422016.Writer) {
//line templates/greetings.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/greetings.qtpl:78
	d.StreamXML(qw422016)
//line templates/greetings.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line templates/greetings.qtpl:78
}

//line templates/greetings.qtpl:78
func (d *MarshalData) XML() string {
//line templates/greetings.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/greetings.qtpl:78
	d.WriteXML(qb422016)
//line templates/greetings.qtpl:78
	qs422016 := string(qb422016.B)
//line templates/greetings.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/greetings.qtpl:78
	return qs422016
//line templates/greetings.qtpl:78
}
