// Code generated by qtc from "prpto.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/prpto.qtpl:1
package templates

//line templates/prpto.qtpl:2
import gen "github.com/pubgo/xprotogen/gen"

//line templates/prpto.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/prpto.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/prpto.qtpl:4
func StreamHeader(qw422016 *qt422016.Writer, pkg string, fd *gen.FileDescriptor) {
//line templates/prpto.qtpl:4
	qw422016.N().S(`
    // Code generated by protoc-gen-micro. DO NOT EDIT.
    `)
//line templates/prpto.qtpl:6
	if fd.GetOptions().GetDeprecated() {
//line templates/prpto.qtpl:6
		qw422016.N().S(`
        // `)
//line templates/prpto.qtpl:7
		fd.StreamGetName(qw422016)
//line templates/prpto.qtpl:7
		qw422016.N().S(` is a deprecated file.
    `)
//line templates/prpto.qtpl:8
	} else {
//line templates/prpto.qtpl:8
		qw422016.N().S(`
        // source: `)
//line templates/prpto.qtpl:9
		fd.StreamGetName(qw422016)
//line templates/prpto.qtpl:9
		qw422016.N().S(`
    `)
//line templates/prpto.qtpl:10
	}
//line templates/prpto.qtpl:10
	qw422016.N().S(`

    package `)
//line templates/prpto.qtpl:12
	qw422016.E().S(pkg)
//line templates/prpto.qtpl:12
	qw422016.N().S(`

    import (
    	fmt "fmt"
    	math "math"
    	context "context"

        client "github.com/asim/go-micro/v3/client"
    	server "github.com/asim/go-micro/v3/server"
    	_ "github.com/gogo/protobuf/gogoproto"
    	proto "github.com/golang/protobuf/proto"
    	_ "google.golang.org/genproto/googleapis/api/annotations"
    )

    // Reference imports to suppress errors if they are not otherwise used.
    var _ = proto.Marshal
    var _ = fmt.Errorf
    var _ = math.Inf

    // This is a compile-time assertion to ensure that this generated file
    // is compatible with the proto package it is being compiled against.
    // A compilation error at this line likely means your copy of the
    // proto package needs to be updated.
    const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

    // Reference imports to suppress errors if they are not otherwise used.
    var _ context.Context
    var _ client.Option
    var _ server.Option
`)
//line templates/prpto.qtpl:41
}

//line templates/prpto.qtpl:41
func WriteHeader(qq422016 qtio422016.Writer, pkg string, fd *gen.FileDescriptor) {
//line templates/prpto.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/prpto.qtpl:41
	StreamHeader(qw422016, pkg, fd)
//line templates/prpto.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line templates/prpto.qtpl:41
}

//line templates/prpto.qtpl:41
func Header(pkg string, fd *gen.FileDescriptor) string {
//line templates/prpto.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/prpto.qtpl:41
	WriteHeader(qb422016, pkg, fd)
//line templates/prpto.qtpl:41
	qs422016 := string(qb422016.B)
//line templates/prpto.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/prpto.qtpl:41
	return qs422016
//line templates/prpto.qtpl:41
}
